Setup aptos-wallet-adapter-tailwind-ui
aptos-labs/aptos-wallet-adapter pull request #29
Opened 2022-12-19 06:21 UTC by WEB3Zer0

2022-12-19 12:54 UTC, 0xmaayan commented
thanks @WEB3Zer0 , it looks good!

I think it might be a good idea to also include the `wallet.icon` on the wallet select modal and an indication whether the wallet is installed, and if not we can add a CTA and redirect them to the `wallet.url` - something like what [aptosnames.com](https://www.aptosnames.com/) has.

Also, it might help to add the new UI to the nextjs-example app so we can see how it looks

2022-12-27 10:21 UTC, 0xmaayan requested changes
Testing it locally and it doesnt seem to load the css correctly.

Also, this packages needs to have tailwind installed and configured.
The main idea is that any app can install this package and uses it regardless of the ui framework the app uses, so this package needs to configure a tailwind ui framework and provide a wallet selector using tailwind-ui design.

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/29798064/209646744-8f12fa7a-9b50-4402-9473-02095994cd45.png">

2022-12-27 10:21 UTC, 0xmaayan commented on apps/nextjs-example/package.json
> +    "@headlessui/react": "^1.7.7",
dont think this is needed here, it should be on the `ui` package.

2022-12-27 10:21 UTC, 0xmaayan commented on apps/nextjs-example/pages/index.tsx
> +import { Menu, Transition } from '@headlessui/react';
can remove it as it is being used on the `ui` package

2022-12-27 10:21 UTC, 0xmaayan commented on apps/nextjs-example/pages/index.tsx
> +import { Fragment, useState } from "react";
can remove it as it is being used on the `ui` package

2022-12-27 10:21 UTC, 0xmaayan commented on apps/nextjs-example/pages/index.tsx
> +    connect
can remove both as it is not being used on this file

2022-12-27 10:21 UTC, 0xmaayan commented on packages/wallet-adapter-tailwind-ui/package.json
> +    "@aptos-labs/wallet-adapter-core": "*",
need to install tailwind on this package 
https://tailwindcss.com/docs/installation

2022-12-27 10:21 UTC, 0xmaayan commented on packages/wallet-adapter-tailwind-ui/src/WalletDropdown.tsx
> +import { WalletReadyState } from '@aptos-labs/wallet-adapter-core';
let's not have this package use `core` as a dependency and instead import and export `WalletReadyState` from the `react` package, same as we do for `WalletName` type.
https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-react/src/useWallet.tsx#L13

I can handle it and publish a new version for `react` package that exports this type.

2022-12-27 15:28 UTC, safaiyeh commented
Oh interesting that it's not rendering on your end. Okay let me set up the tailwind config

2022-12-27 16:26 UTC, WEB3Zer0 commented
Thanks for the review @0xmaayan! Odd that its not rendering on next.js but working locally, ill address the comments.

2022-12-28 10:38 UTC, 0xmaayan commented
> Thanks for the review @0xmaayan! Odd that its not rendering on next.js but working locally, ill address the comments.

Hi @WEB3Zer0 , I tested it locally with the demo app (it is a nextjs app), I do it with running `pnpm turbo run dev` on the root of this monorepo
https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/CONTRIBUTING.md#develop-locally

2022-12-28 10:38 UTC, 0xmaayan commented on packages/wallet-adapter-tailwind-ui/src/WalletDropdown.tsx
> +import { WalletReadyState } from '@aptos-labs/wallet-adapter-core';
@WEB3Zer0 https://github.com/aptos-labs/aptos-wallet-adapter/pull/36
once approved I can bump the version and you can update and use it

2023-01-12 04:28 UTC, closed without merging