Add AptosConnect Id
aptos-labs/aptos-wallet-adapter pull request #334
Opened 2024-06-24 04:56 UTC by kent-white

2024-06-24 04:58 UTC, hardsetting approved these changes

2024-06-24 14:11 UTC, 0xmaayan approved these changes
Please update changeset to include it in the next release.

Also, can we update the react package README file with this update? https://github.com/aptos-labs/aptos-wallet-adapter/tree/main/packages/wallet-adapter-react#available-provider-props

2024-06-24 16:03 UTC, 0xmaayan commented on packages/wallet-adapter-core/src/AIP62StandardWallets/sdkWallets.ts
> +export function getSDKWallets(dappConfig?: DappConfig) {
nit
```
const { network, dappId } = dappConfig
```

2024-06-24 16:05 UTC, 0xmaayan commented on packages/wallet-adapter-react/src/WalletProvider.tsx
> +import { DappConfig } from "@aptos-labs/wallet-adapter-core/dist/WalletCore";
```suggestion
import { DappConfig } from "@aptos-labs/wallet-adapter-core";
```

2024-06-24 16:07 UTC, 0xmaayan commented on packages/wallet-adapter-core/src/WalletCore.ts
> +export interface DappConfig {
youd need to explicitly export this type so dapps can use it
https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/src/index.ts#L3

we should probably move those types/interfaces to `types.ts` file or something and just export this whole file

2024-06-24 16:08 UTC, 0xmaayan commented on packages/wallet-adapter-core/src/WalletCore.ts
> +  aptosConnectDappId?: string;
curios, whats happens if dapp doesnt provide a dappID for AptosConnect?

2024-06-24 16:09 UTC, 0xmaayan commented on packages/wallet-adapter-react/src/WalletProvider.tsx
> +import { DappConfig } from "@aptos-labs/wallet-adapter-core/dist/WalletCore";
I think youd need to export the DappConfig type from the core package to use it.

2024-06-24 16:11 UTC, 0xmaayan requested changes
we need to export the new type so 
- dapps can use it
- react package to import it from the core package and not from the dist folder

2024-06-26 16:30 UTC, 0xmaayan approved these changes

2024-06-26 16:35 UTC, merged

2024-06-27 20:06 UTC, kent-white commented on packages/wallet-adapter-core/src/WalletCore.ts
> +  aptosConnectDappId?: string;
the IC legacy accounts aren't shown.

2024-06-27 20:06 UTC, kent-white commented on packages/wallet-adapter-core/src/AIP62StandardWallets/sdkWallets.ts
> +export function getSDKWallets(dappConfig?: DappConfig) {
i dont think you can destructure optional nicely like this?